.TH HYBRID 1 "JULY 2014"

.SH NAME
Hybrid \- Multi platform Qt based encoding frontend

.SH SYNOPSIS
.B hybrid \fR[-version]
.br
.B hybrid-qt46 \fR[-version]
.br
.B hybrid-qt5 \fR[-version]

.SH OPTIONS
.B hybrid\fR: linked against Qt 4.8
.br
.B hybrid-qt46\fR: linked against Qt 4.6
.br
.B hybrid-qt5\fR: linked against Qt 5.2.1
.TP
.B \-version
Displays the current version and quits.

.SH DESCRIPTION
.B Hybrid
can convert nearly every input to x264/x265/Xvid/VP9/... + ac3/ogg/mp3/aac/flac
inside an mp4/m2ts/mkv/webm/mov/avi container, a Blu-ray or an AVCHD structure.

Here's a general feature list:
 * extensive ability to configure x264's setting (with dependency checks)
 * ability to configure x265's setting
 * tagging support for mkv/mp4/mov
 * chapter support for mkv/mp4/Blu-ray
 * subtitle suppot for mkv/mp4/Blu-ray
 * separated audio-, video-, filter profiles, audio&video combi profiles
 * an integrated bitrate calculator
 * accepts vc-1 and avc raw input
 * manual & automatic creation & pass-through of chapters
 * ability to encode single title/chapters
 * a job-control
 * aac/mp3/ac3/ogg/flac/dts/pcm audio encoding with
   dcaenc/mencoder/ffmpeg/aften and different aac encoders
 * supported aac encoders: qaac, fdk, faac, fhg, neroaacenc, vo-aacenc
 * filtering through mencoder (+ some resize automation)
 * acceptable Input: avs and everything that mplayer/ffmpeg can decode
 * supported video output formats: MPEG-4 ASP (Xvid), MPEG-4 AVC
   (x264, cuda, qsvencc), VP8/VP9 (vpxenc), ProRes (ffmpeg), MPEG-4 HEVC
   (x265, kvazaar, DivX265), FFV1 (ffmpeg), UT video (ffmpeg), FFvHuff (ffmpeg)
 * supported audio output formats: dts, ac3, ogg vorbis, mp3, aac, flac, pcm,
   opus, pass-through
 * supported containers: mov/mp4/mkv/m2ts/webm/avi, Blu-ray or a AVCHD
   structure
 * audio/video pass-through -> can be used for muxing, tagging, chapter editing
 * a lot of option to automate stuff

An Avisynth extension to enable Avisynth script generation is available too.
It has to be downloaded manually and requires
.BR wine (1)
to work:
.I http://www.selur.de/downloads

.SH SEE ALSO
.I http://www.selur.de/

.SH AUTHOR
Hybrid was written by Selur <\fIhybrid@selur.de\fR> and is under a proprietary license.
The wrapper scripts and the Debian packaging were done by djcj <\fIdjcj@gmx.de\fR> and
are released under MIT license.
The desktop icons were taken from the Oxygen icon theme, which is available under LGPL-3.
