.TH HYBRID 1 "February 2016"

.SH NAME
Hybrid \- Multi platform Qt based encoding frontend

.SH SYNOPSIS
.B hybrid \fR[options] [<QT options>]

.SH OPTIONS
.TP
.B \-\-log
save a log file in
.I ~/.hybrid/logs/
.TP
.B \-\-no\-update
don't check for available updates on startup
.TP
.B \-\-disable-updates
disable automatic updates
.TP
.B \-\-enable-updates
enable automatic updates
.TP
.B \-\-rollback
Switch back to the previous version if a backup is available.
This disables automatic updates.
A backup of the currently installed version is automatically saved in
.I ~/.hybrid\-bin/
when upgrading to a new version.
.TP
.B \-h\fR, \fB\-\-help
show usage information
.TP
.B \-V\fR, \fB\-\-version
show the current version and quit

.SH DESCRIPTION
.B Hybrid
can convert nearly every input to x264/x265/Xvid/VP9/... + ac3/ogg/mp3/aac/flac
inside an mp4/m2ts/mkv/webm/mov/avi container, a Blu\-ray or an AVCHD structure.

Here's a general feature list:
 * extensive ability to configure x264's setting (with dependency checks)
 * ability to configure x265's setting
 * tagging support for mkv/mp4/mov
 * chapter support for mkv/mp4/Blu\-ray
 * subtitle suppot for mkv/mp4/Blu\-ray
 * separated audio\-, video\-, filter profiles, audio&video combi profiles
 * an integrated bitrate calculator
 * accepts vc\-1 and avc raw input
 * manual & automatic creation & pass\-through of chapters
 * ability to encode single title/chapters
 * a job\-control
 * aac/mp3/ac3/ogg/flac/dts/pcm audio encoding with
   dcaenc/mencoder/ffmpeg/aften and different aac encoders
 * supported aac encoders: qaac, fdk, faac, fhg, neroaacenc, vo\-aacenc
 * filtering through mencoder (+ some resize automation)
 * acceptable Input: avs and everything that mplayer/ffmpeg can decode
 * supported video output formats: MPEG\-4 ASP (Xvid), MPEG\-4 AVC
   (x264, cuda, qsvencc), VP8/VP9 (vpxenc), ProRes (ffmpeg), MPEG\-4 HEVC
   (x265, kvazaar, DivX265), FFV1 (ffmpeg), UT video (ffmpeg), FFvHuff (ffmpeg)
 * supported audio output formats: dts, ac3, ogg vorbis, mp3, aac, flac, pcm,
   opus, pass\-through
 * supported containers: mov/mp4/mkv/m2ts/webm/avi, Blu\-ray or a AVCHD
   structure
 * audio/video pass\-through \-> can be used for muxing, tagging, chapter editing
 * a lot of option to automate stuff

.SS "Using AviSynth"
You can enable AviSynth by installing the \fIhybrid\-avisynth\-extension\fR package.
Keep in mind that this will install
.BR wine (1).

.SS Dependencies
Hybrid uses quite a bunch of other tools the background.
You can install all the required tools at once with the meta package \fIhybrid\-tools\fR.
.PP
This metapackage will install the following tools:
.br
.BR aac-enc (1),
.BR aften (1),
.BR bdsup2sub++ (1),
.BR dcaenc (1),
.BR delaycut (1),
.BR divx265 (1),
.BR faac (1),
.BR ffmbc (1),
.BR ffmpeg (1),
.BR flac (1),
.BR FLVExtractCL (1),
.BR framecounter (1),
.BR kvazaar (1),
.BR lame (1),
.BR lsdvd (1),
.BR mediainfo (1),
.BR mencoder (1),
.BR mkvextract (1),
.BR mkvinfo (1),
.BR mkvmerge (1),
.BR mp4fpsmod (1),
.BR MP4Box (1),
.BR mplayer (1)
or
.BR mplayer2 (1),
.BR neroaacenc (1),
.BR oggenc (1),
.BR opusenc (1),
.BR sox (1),
.BR telxcc (1),
.BR tsmuxer (1),
.BR vpxenc (1),
.BR x264 (1),
.BR x264-10bit (1),
and
.BR x265 (1).

.SH "SEE ALSO"
Configuration files are located in \fI~/.hybrid/\fR
.br
Hybrid's executable binary file is located in \fI~/.hybrid\-bin/\fR
.PP
Official homepage:
.I http://www.selur.de/
.PP
Wrapper scripts and Debian package sources:
.br
.I https://github.com/darealshinji/hybrid\-debian
.br
.I https://github.com/darealshinji/hybrid-debian/tree/avisynth-extension

.SH AUTHOR
Hybrid was written by Selur <\fIhybrid@selur.de\fR> and is released under a proprietary freeware license.
The wrapper scripts and the Debian packaging were made by djcj <\fIdjcj@gmx.de\fR> and are released under MIT license.
The desktop icons were taken from the Oxygen icon theme, which is available under LGPL v3.
