.TH HYBRID 1 "NOVEMBER 2014"

.SH NAME
Hybrid \- Multi platform Qt based encoding frontend

.SH SYNOPSIS
.B hybrid \fR[options]
.br
.B hybrid-qt5 \fR[options]

.SH OPTIONS
.B \-version
displays the current version and quits
.TP
.B \-log
saves a log file in
.I ~/.hybrid/logs/

.SH DESCRIPTION
.B Hybrid
can convert nearly every input to x264/x265/Xvid/VP9/... + ac3/ogg/mp3/aac/flac
inside an mp4/m2ts/mkv/webm/mov/avi container, a Blu-ray or an AVCHD structure.

Here's a general feature list:
 * extensive ability to configure x264's setting (with dependency checks)
 * ability to configure x265's setting
 * tagging support for mkv/mp4/mov
 * chapter support for mkv/mp4/Blu-ray
 * subtitle suppot for mkv/mp4/Blu-ray
 * separated audio-, video-, filter profiles, audio&video combi profiles
 * an integrated bitrate calculator
 * accepts vc-1 and avc raw input
 * manual & automatic creation & pass-through of chapters
 * ability to encode single title/chapters
 * a job-control
 * aac/mp3/ac3/ogg/flac/dts/pcm audio encoding with
   dcaenc/mencoder/ffmpeg/aften and different aac encoders
 * supported aac encoders: qaac, fdk, faac, fhg, neroaacenc, vo-aacenc
 * filtering through mencoder (+ some resize automation)
 * acceptable Input: avs and everything that mplayer/ffmpeg can decode
 * supported video output formats: MPEG-4 ASP (Xvid), MPEG-4 AVC
   (x264, cuda, qsvencc), VP8/VP9 (vpxenc), ProRes (ffmpeg), MPEG-4 HEVC
   (x265, kvazaar, DivX265), FFV1 (ffmpeg), UT video (ffmpeg), FFvHuff (ffmpeg)
 * supported audio output formats: dts, ac3, ogg vorbis, mp3, aac, flac, pcm,
   opus, pass-through
 * supported containers: mov/mp4/mkv/m2ts/webm/avi, Blu-ray or a AVCHD
   structure
 * audio/video pass-through -> can be used for muxing, tagging, chapter editing
 * a lot of option to automate stuff

.SS "Qt version"
.B hybrid\fR is linked against Qt 4.8 and
.B hybrid-qt5\fR is linked against Qt 5.2.1.

.SS "Using AviSynth"
You can enable AviSynth by installing the \fIhybrid-avisynth-extension\fR package.
Keep in mind that this will install
.BR wine (1).

.SH "SEE ALSO"
Configuration files are located in \fI~/.hybrid/\fR
.br
Hybrid's executable binary file is located in \fI~/.hybrid-bin/\fR
.PP
Official homepage:
.I http://www.selur.de/
.PP
Wrapper scripts and Debian package sources:
.br
.I https://github.com/darealshinji/hybrid-debian
.br
.I https://github.com/darealshinji/hybrid-avisynth-extension

.SH AUTHOR
Hybrid was written by Selur <\fIhybrid@selur.de\fR> and is released under a proprietary freeware license.
The wrapper scripts and the Debian packaging were done by djcj <\fIdjcj@gmx.de\fR> and
are released under MIT license.
The desktop icons were taken from the Oxygen icon theme, which is available under LGPL v3.
